import React,{useState,useEffect} from 'react';
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  let streakArray = 
  [
    "7-9-2022",
    "7-10-2022"
  ];

  let currentTime = new Date();
  let month = 1+currentTime.getMonth();
  let day = currentTime.getDate();
  let year = currentTime.getFullYear();

  let dateString = month+"-"+day+"-"+year;
  // console.log(dateString);

  const lastItem = streakArray[streakArray.length - 1];
  // console.log(lastItem);

  return (

    
    

    <div className={styles.container}>
      <Head>
        <title>Do the thing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-pink-500 text-center h- p-8 text-white rounded-xl m-12">
        <h1>{dateString == lastItem ? "You did the thing!" : "You have time do the thing :)"}</h1>
      </div>

      <div>
        
      </div>

    </div>
  );
}
